Repository rsksmart/rif-identity.js, pull requests merged in 2020-10, with the labels that each got.

#61 v0.1.0
  README.md
  lerna.json
  packages/rif-id-core/package-lock.json
  packages/rif-id-core/package.json
  packages/rif-id-daf/package-lock.json
  packages/rif-id-daf/package.json
  packages/rif-id-ethr-did/package-lock.json
  packages/rif-id-ethr-did/package.json
  packages/rif-id-mnemonic/package-lock.json
  packages/rif-id-mnemonic/package.json
Labels: dependencies

#64 Express did auth implementation
  packages/express-did-auth/README.md
  packages/express-did-auth/package-lock.json
  packages/express-did-auth/package.json
  packages/express-did-auth/src/classes/challenge-verifier.ts
  packages/express-did-auth/src/classes/request-counter.ts
  packages/express-did-auth/src/classes/session-manager.ts
  packages/express-did-auth/src/config-adapters.ts
  packages/express-did-auth/src/constants.ts
  packages/express-did-auth/src/defaults.ts
  packages/express-did-auth/src/errors.ts
  packages/express-did-auth/src/factories/authentication-factory.ts
  packages/express-did-auth/src/factories/express-middleware-factory.ts
  packages/express-did-auth/src/factories/index.ts
  packages/express-did-auth/src/factories/logout-factory.ts
  packages/express-did-auth/src/factories/refresh-token-factory.ts
  packages/express-did-auth/src/factories/request-auth-factory.ts
  packages/express-did-auth/src/factories/request-signup-factory.ts
  packages/express-did-auth/src/index.ts
  packages/express-did-auth/src/jwt-utils.ts
  packages/express-did-auth/src/types.ts
  packages/express-did-auth/test/authentication-factory.test.ts
  packages/express-did-auth/test/challenge-verifier.test.ts
  packages/express-did-auth/test/express-middleware-factory.test.ts
  packages/express-did-auth/test/jwt-utils.test.ts
  packages/express-did-auth/test/logout-factory.test.ts
  packages/express-did-auth/test/refresh-token-factory.test.ts
  packages/express-did-auth/test/request-auth-factory.test.ts
  packages/express-did-auth/test/request-counter.test.ts
  packages/express-did-auth/test/request-signup-factory.test.ts
  packages/express-did-auth/test/session-manager.test.ts
  packages/express-did-auth/test/setup-app.cookies.integration.test.ts
  packages/express-did-auth/test/setup-app.middleware.test.ts
  packages/express-did-auth/test/setup-app.no-cookies.integration.test.ts
  packages/express-did-auth/test/utils.ts
  packages/express-did-auth/tsconfig.json
  packages/tsconfig.json
Labels: enhancement

#67 Fixes before release
  packages/express-did-auth/README.md
  packages/express-did-auth/package.json
Labels: bug, documentation
