Repository rsksmart/rif-identity.js, pull requests merged in 2020-09, with the labels that each got.

#50 Issue credential requests
  package-lock.json
  package.json
  packages/rif-id-core/package-lock.json
  packages/rif-id-core/package.json
  packages/rif-id-core/src/entities/CredentialRequest.ts
  packages/rif-id-core/src/entities/index.ts
  packages/rif-id-core/src/operations/credentialRequests.ts
  packages/rif-id-core/src/reducers/issuedCredentialRequests.ts
  packages/rif-id-core/test/entities/CredentialRequest.test.ts
  packages/rif-id-core/test/operations/credentialRequests.test.ts
  packages/rif-id-core/test/operations/identity.test.ts
  packages/rif-id-core/test/reducers/issuedCredentialRequests.test.ts
  packages/rif-id-core/test/util.ts
Labels: enhancement

#53 Fix ethr did
  packages/rif-id-core/test/operations/credentials.test.ts
  packages/rif-id-daf/package-lock.json
  packages/rif-id-daf/package.json
  packages/rif-id-daf/src/key-management-system.ts
  packages/rif-id-daf/test/daf.integration.test.ts
  packages/rif-id-daf/test/identity-provider.test.ts
  packages/rif-id-ethr-did/README.md
  packages/rif-id-ethr-did/package-lock.json
  packages/rif-id-ethr-did/package.json
  packages/rif-id-ethr-did/src/index.ts
  packages/rif-id-ethr-did/src/rskAddress.ts
  packages/rif-id-ethr-did/src/rskDID.ts
  packages/rif-id-ethr-did/src/types.d.ts
  packages/rif-id-ethr-did/test/rskAddress.test.ts
  packages/rif-id-ethr-did/test/rskDID.test.ts
Labels: bug, enhancement

#55 Bump version
  packages/rif-id-core/package.json
Labels: dependencies

#49 Authentication module
  .gitignore
  README.md
  package-lock.json
  packages/rif-id-core/package-lock.json
  packages/rif-id-core/package.json
  packages/rif-id-core/src/operations/authentication.ts
  packages/rif-id-core/src/reducers/authentication.ts
  packages/rif-id-core/test/operations/authentication.test.ts
  packages/rif-id-core/test/reducers/authentication.test.ts
  packages/rif-id-core/test/util.ts
Labels: enhancement

#59 Enable credential requests with headers
  packages/rif-id-core/package-lock.json
  packages/rif-id-core/package.json
  packages/rif-id-core/src/operations/credentialRequests.ts
  packages/rif-id-core/test/operations/credentialRequests.test.ts
  packages/rif-id-core/test/util.ts
  packages/rif-id-daf/package-lock.json
  packages/rif-id-daf/package.json
  packages/rif-id-daf/src/did-comm-action-handler.ts
Labels: daf
